server:
  port: 8080
#
#
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/store_db
#    username: postgres
#    password: 123456
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#
#springdoc:
#  api-docs:
#    path: /v3/api-docs
#  swagger-ui:
#    path: /swagger-ui.html

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/store_db
    username: postgres
    password: 123456
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html